name: pms
services:
    mongo:
        hostname: a0dbc72a2bb0
        mac_address: 02:42:ac:11:00:02
        environment:
            - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - GOSU_VERSION=1.16
            - JSYAML_VERSION=3.13.1
            - MONGO_PACKAGE=mongodb-org
            - MONGO_REPO=repo.mongodb.org
            - MONGO_MAJOR=7.0
            - MONGO_VERSION=7.0.2
            - HOME=/data/db
        volumes:
            - /data/configdb
            - /data/db
        ports:
            - 27017:27017
        labels:
            - org.opencontainers.image.ref.name=ubuntu
            - org.opencontainers.image.version=22.04
        runtime: runc
        image: mongo:latest